import type { Metadata } from "next";
import styles from "../legal.module.css";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "ToolNest terms of service. Usage terms, disclaimers, and limitations of liability.",
};

export default function TermsPage() {
  return (
    <div className={styles.legalPage}>
      <div className={styles.container}>
        <h1 className={styles.title}>Terms of Service</h1>
        <p className={styles.lastUpdated}>Last updated: August 2026</p>

        <section className={styles.section}>
          <h2>Acceptance of Terms</h2>
          <p>
            By accessing and using ToolNest, you agree to be bound by these
            Terms of Service. If you do not agree with any part of these terms,
            please do not use our website.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Description of Service</h2>
          <p>
            ToolNest provides free online developer and utility tools that
            process data entirely in your web browser. Our tools are provided
            &quot;as is&quot; and &quot;as available&quot; without any warranties
            of any kind.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Use of Tools</h2>
          <p>You may use ToolNest tools for any lawful purpose. You agree not to:</p>
          <ul>
            <li>
              Use our tools to process illegal, harmful, or malicious content.
            </li>
            <li>
              Attempt to interfere with or disrupt the website or its
              infrastructure.
            </li>
            <li>
              Scrape, crawl, or otherwise extract content from the site in an
              automated manner that places undue burden on our infrastructure.
            </li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>Disclaimer of Warranties</h2>
          <p>
            ToolNest tools are provided for informational and utility purposes
            only. We make no guarantees regarding the accuracy, reliability, or
            completeness of any tool&apos;s output. You should always verify
            results independently, especially for critical applications.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Limitation of Liability</h2>
          <p>
            In no event shall ToolNest be liable for any direct, indirect,
            incidental, special, consequential, or punitive damages arising
            from your use of our tools or website.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Intellectual Property</h2>
          <p>
            The ToolNest website design, logo, and original content are our
            intellectual property. The tools themselves use standard algorithms
            and open-source libraries. Any output generated by the tools belongs
            to you.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Changes to Terms</h2>
          <p>
            We reserve the right to update these terms at any time. Changes
            will be reflected by updating the &quot;Last updated&quot; date. Continued
            use of the website after changes constitutes acceptance of the
            revised terms.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Contact</h2>
          <p>
            If you have questions about these terms, please{" "}
            <a href="/contact/">contact us</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
